export const TURNOS_REQUEST = 'TURNOS_REQUEST';
export const TURNOS_FAIL = 'TURNOS_FAIL';
export const TURNOS_GET_ALL_BY_AREA_ID = 'TURNOS_GET_ALL_BY_AREA_ID';
export const TURNOS_GET_ALL_AREAS = 'TURNOS_GET_ALL_AREAS';
export const TURNOS_UPDATE_STATUS = 'TURNOS_UPDATE_STATUS';
export const TURNOS_GET_BY_MONTH = 'TURNOS_GET_BY_MONTH';
export const TURNOS_RESERVAR = 'TURNOS_RESERVAR';
