export const TURNOS_REQUEST = 'TURNOS_REQUEST';
export const TURNOS_FAIL = 'TURNOS_FAIL';
export const TURNOS_GET_BY_MONTH = 'TURNOS_GET_BY_MONTH';
export const TURNOS_RESERVAR = 'TURNOS_RESERVAR';
export const TUNROS_RESERVAR_FISCALIZACION = 'TUNROS_RESERVAR_FISCALIZACION';
