#!/bin/bash
# export HOST=asoccsdv.svr110.vcnprod.oraclevcn.com
export ORACLE_HOME=/usr/lib/oracle/21/client64/lib/network/admin
export TNS_ADMIN=/usr/lib/oracle/21/client64/lib/network/admin
export ORACLE_SID=fincomun
export Service=fincomun
export DOMAIN=svr110.vcnprod.oraclevcn.com
export DATABASE_NAME=FINCOMUN
export DATABASE_PORT=1522
export DATABASE_PASSWORD=AS0ccdV!!01
export DATABASE_USER=FINCOMUN
export DATABASE_HOST=10.200.110.111
export API_KEY=asd
export JWT_SECRET=asd
export API_HOST=127.0.0.1
export FILES_HOST=ash-db19dv.svr110.vcnprod.oraclevcn.com:3001
export LANDING_URL=ash-db19dv.svr110.vcnprod.oraclevcn.com:3001
export MODE=DEV
export RUN_MIGRATIONS=true
export PORT=3001
export DEFAULTLOCALE=es
export FILES_PATH=/opt/oracle/fincomun-files
export MAIL_HOST=smtp.gmail.com
export MAIL_USER=mailling@gigigo.com
export MAIL_PASS=vzrjaeghogjfemyw
export MAIL_FROM=mailling@gigigo.com
export AUTH_TOKEN='Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6IlNVUEVSQURNSU4iLCJlbWFpbCI6ImthcmVuLmFsdmFyYWRvQGVjb25vY29tLmNvbSIsImRhdGUiOiIyMDIyLTA3LTA3VDIxOjM3OjE3LjY5N1oiLCJpYXQiOjE2NTcyMjk4MzcsImV4cCI6MTY1ODA5MzgzN30.KWNnHZrsxq4qzTblRJ0yIGnQTOacX81ONIE9zp1zTqo'
export HOST=http://localhost:3001/
export FINCOMUN_API=https://mobileqa.fincomun.com.mx/APAVAN/
# export NODE_TLS_REJECT_UNAUTHORIZED='0'
export PATH=/usr/lib/oracle/21/client64/bin:$PATH