export const listaBarrios = [
    {value: 1, label: "Agronomía"},
    {value: 2, label: "Almagro"},
    {value: 3, label: "Balvanera"},
    {value: 4, label: "Barracas"},
    {value: 5, label: "Belgrano"},
    {value: 6, label: "Boedo"},
    {value: 7, label: "Caballito"},
    {value: 8, label: "Chacarita"},
    {value: 9, label: "Coghlan"},
    {value: 10, label: "Colegiales"},
    {value: 11, label: "Constitución"},
    {value: 12, label: "Flores"},
    {value: 13, label: "Floresta"},
    {value: 14, label: "La Boca"},
    {value: 15, label: "Paternal"},
    {value: 16, label: "Liniers"},
    {value: 17, label: "Mataderos"},
    {value: 18, label: "Monte Castro"},
    {value: 19, label: "Monserrat"},
    {value: 20, label: "Nueva Pompeya"},
    {value: 21, label: "Núñez"},
    {value: 22, label: "Palermo"},
    {value: 23, label: "Parque Avellaneda"},
    {value: 24, label: "Parque Chacabuco"},
    {value: 25, label: "Parque Chas"},
    {value: 26, label: "Parque Patricios"},
    {value: 27, label: "Puerto Madero"},
    {value: 28, label: "Recoleta"},
    {value: 29, label: "Retiro"},
    {value: 30, label: "Saavedra"},
    {value: 31, label: "San Cristóbal"},
    {value: 32, label: "San Nicolás"},
    {value: 33, label: "San Telmo"},
    {value: 34, label: "Versalles"},
    {value: 35, label: "Villa Crespo"},
    {value: 36, label: "Villa Devoto"},
    {value: 37, label: "Villa General Mitre"},
    {value: 38, label: "Villa Lugano"},
    {value: 39, label: "Villa Luro"},
    {value: 40, label: "Villa Ortúzar"},
    {value: 41, label: "Villa Pueyrredón"},
    {value: 42, label: "Villa Real"},
    {value: 43, label: "Villa Riachuelo"},
    {value: 44, label: "Villa Santa Rita"},
    {value: 45, label: "Villa Soldati"},
    {value: 46, label: "Villa Urquiza"},
    {value: 47, label: "Villa del Parque"},
    {value: 48, label: "Vélez Sarsfield"}
]
