export const rankingLeadershipCmsMockUp = [
  {
    id: 1,
    level: 'Líder Plata',
    status: 1,
    apply_since: '2022-03-31 18:00:00',
    minimal_associates: 20,
    associate_type: 'Directos',
    minimum_outlay: 40,
    min_act_percentage: 50,
    trainging_status: true,
  },
  {
    id: 2,
    level: 'Líder Bronce',
    status: 1,
    apply_since: '2022-03-31 18:00:00',
    minimal_associates: 10,
    associate_type: 'Directos',
    minimum_outlay: 30,
    min_act_percentage: 35,
    trainging_status: true,
  },
  {
    id: 3,
    level: 'Futuro Líder',
    status: 1,
    apply_since: '2022-03-31 18:00:00',
    minimal_associates: 1,
    associate_type: 'Directos',
    minimum_outlay: 0,
    min_act_percentage: 0,
    trainging_status: false,
  },
];
