export const commissionMockUps = [
  {
    id: 1,
    commissionName: 'Consultas',
    conceptId: 1,
    typeCommissionId: 1,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 4,
    calculationBasis: 'Total de consultas de la semana',
    rule: 'Mayor o igual a 10',
    ruleValue: 'Mayor o igual a ',
    measurmentUnitId: 1,
    measurment_value: 250,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 10,
  },
  {
    id: 2,
    commissionName: 'Colocación semanal 1',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 1,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Menor que 5',
    ruleValue: 'Menor que',
    measurmentUnitId: 2,
    measurment_value: 5,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 3,
    commissionName: 'Colocación semanal 2',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 1,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Mayor o igual a 5',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 2,
    measurment_value: 6,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 4,
    commissionName: 'Colocación semanal 3',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 2,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Menor que 5',
    ruleValue: 'Menor que',
    measurmentUnitId: 2,
    measurment_value: 5,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 5,
    commissionName: 'Colocación semanal 4',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 2,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Mayor o igual a 5',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 2,
    measurment_value: 6,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 6,
    commissionName: 'Colocación semanal 5',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 3,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Menor que 5',
    ruleValue: 'Menor que',
    measurmentUnitId: 2,
    measurment_value: 6,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 7,
    commissionName: 'Colocación semanal 6',
    conceptId: 2,
    typeCommissionId: 2,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 3,
    calculationBasis: 'Cantidad de Desembolsos semanal',
    rule: 'Mayor o igual a 5',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 2,
    measurment_value: 7,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 5,
  },
  {
    id: 8,
    commissionName: 'Recompra Digital 1',
    conceptId: 3,
    typeCommissionId: 3,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 1,
    calculationBasis: '1er Recompra Digital',
    rule: '',
    ruleValue: '',
    measurmentUnitId: 2,
    measurment_value: 1,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 0,
  },
  {
    id: 9,
    commissionName: 'Recompra Digital 2',
    conceptId: 3,
    typeCommissionId: 3,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 2,
    calculationBasis: '1er Recompra Digital',
    rule: '',
    ruleValue: '',
    measurmentUnitId: 2,
    measurment_value: 2,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 0,
  },
  {
    id: 10,
    commissionName: 'Recompra Digital 3',
    conceptId: 3,
    typeCommissionId: 3,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 3,
    calculationBasis: '1er Recompra Digital',
    rule: '',
    ruleValue: '',
    measurmentUnitId: 2,
    measurment_value: 3,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 0,
  },
  {
    id: 11,
    commissionName: 'Bono Mensual',
    conceptId: 4,
    typeCommissionId: 4,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 4,
    calculationBasis: 'Cantidad de Desembolsos mensual',
    rule: 'mayor que 6',
    ruleValue: 'mayor que',
    measurmentUnitId: 2,
    measurment_value: 1,
    paymentChronologyId: 2,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 6,
  },
  {
    id: 12,
    commissionName: 'Caso al Corriente',
    conceptId: 5,
    typeCommissionId: 5,
    ranking: 'Individual',
    group: 'Crédito',
    levelId: 4,
    calculationBasis: '1er Caso al Corriente',
    rule: '',
    ruleValue: '',
    measurmentUnitId: 1,
    measurment_value: 100,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 0,
  },
  {
    id: 13,
    commissionName: 'Consultas',
    conceptId: 1,
    typeCommissionId: 1,
    ranking: '',
    group: 'Crédito',
    levelId: 8,
    calculationBasis: 'Cantidad de consultas mensual',
    rule: 'Consultas',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 300,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 30,
  },
  {
    id: 14,
    commissionName: 'Pago por Crédito 1',
    conceptId: 6,
    typeCommissionId: 3,
    ranking: '',
    group: 'Crédito',
    levelId: 5,
    calculationBasis: 'Cantidad de desembolsos red',
    rule: 'Desembolsos',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 100,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 1,
  },
  {
    id: 15,
    commissionName: 'Pago por Crédito 2',
    conceptId: 6,
    typeCommissionId: 3,
    ranking: '',
    group: 'Crédito',
    levelId: 7,
    calculationBasis: 'Cantidad de desembolsos red',
    rule: 'Desembolsos',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 225,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 1,
  },
  {
    id: 16,
    commissionName: 'Pago por Crédito 3',
    conceptId: 6,
    typeCommissionId: 3,
    ranking: '',
    group: 'Crédito',
    levelId: 6,
    calculationBasis: 'Cantidad de desembolsos red',
    rule: 'Desembolsos',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 275,
    paymentChronologyId: 1,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 1,
  },
  {
    id: 17,
    commissionName: 'Meta Cumplida 2',
    conceptId: 6,
    typeCommissionId: 4,
    ranking: '',
    group: 'Crédito',
    levelId: 7,
    calculationBasis: 'Cantidad de desembolsos red',
    rule: 'Desembolsos',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 100,
    paymentChronologyId: 2,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 15,
  },
  {
    id: 18,
    commissionName: 'Meta Cumplida 3',
    conceptId: 6,
    typeCommissionId: 4,
    ranking: '',
    group: 'Crédito',
    levelId: 6,
    calculationBasis: 'Cantidad de desembolsos red',
    rule: 'Desembolsos',
    ruleValue: 'Mayor o igual a',
    measurmentUnitId: 1,
    measurment_value: 100,
    paymentChronologyId: 2,
    apply_since: '2010-05-22',
    is_active: 1,
    ruleComputeValue: 20,
  },
];
