export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_FAIL = 'USERS_FAIL';
export const USERS_GET_MATRICULADOS = 'USERS_GET_MATRICULADOS';
export const GET_HOME_INFO = 'GET_HOME_INFO';
export const GET_USUARIOS_CON_CARPETA = 'GET_USUARIOS_CON_CARPETA';
export const GET_USUARIO = 'GET_USUARIO';
