import { TypeOfUser, UserEnumStatus } from '../../config/enum-types';
export const adminUserMockUp = [
	{
		firstName: 'Cucicba',
		lastName: 'Admin',
		email: 'admin1@mail.com',
		dni: '3333331',
		phoneNumber: '543472552354',
		typeOfUser: TypeOfUser.adminUser,
		status: UserEnumStatus.active,
		password: 'Cucicba123.',
		confirmPassword: 'Cucicba123.',
		realEstateId: 1,
	},
	{
		firstName: 'Cucicba',
		lastName: 'Admin',
		email: 'admin2@mail.com',
		dni: '3333332',
		phoneNumber: '543472552354',
		typeOfUser: TypeOfUser.adminUser,
		status: UserEnumStatus.active,
		password: 'Cucicba123.',
		confirmPassword: 'Cucicba123.',
		realEstateId: 2,
	},
	{
		firstName: 'Cucicba',
		lastName: 'Admin',
		email: 'admin3@mail.com',
		dni: '3333333',
		phoneNumber: '543472552354',
		typeOfUser: TypeOfUser.adminUser,
		status: UserEnumStatus.active,
		password: 'Cucicba123.',
		confirmPassword: 'Cucicba123.',
		realEstateId: 3,
	},
	{
		firstName: 'Cucicba',
		lastName: 'Admin',
		email: 'admin4@mail.com',
		dni: '3333334',
		phoneNumber: '543472552354',
		typeOfUser: TypeOfUser.adminUser,
		status: UserEnumStatus.active,
		password: 'Cucicba123.',
		confirmPassword: 'Cucicba123.',
		realEstateId: 4,
	},
	{
		firstName: 'Cucicba',
		lastName: 'Admin',
		email: 'admin5@mail.com',
		dni: '3333335',
		phoneNumber: '543472552354',
		typeOfUser: TypeOfUser.adminUser,
		status: UserEnumStatus.active,
		password: 'Cucicba123.',
		confirmPassword: 'Cucicba123.',
		realEstateId: 5,
	},
];
