export const ambienceTypesMockUp = [
	{ ambienceType: 'Balcón' },
	{ ambienceType: 'Dormitorio en suite' },
	{ ambienceType: 'Living comedor' },
	{ ambienceType: 'Baulera' },
	{ ambienceType: 'Escritorio' },
	{ ambienceType: 'Patio' },
	{ ambienceType: 'Cocina' },
	{ ambienceType: 'Hall' },
	{ ambienceType: 'Sótano' },
	{ ambienceType: 'Comedor' },
	{ ambienceType: 'Jardín' },
	{ ambienceType: 'Terraza' },
	{ ambienceType: 'Comedor de diario' },
	{ ambienceType: 'Lavadero' },
	{ ambienceType: 'Toilette' },
	{ ambienceType: 'Dependencia de servicio' },
	{ ambienceType: 'Living' },
	{ ambienceType: 'Vestidor' },
];
