export const gralCharacteristicsMockUp = [
	{ name: 'Aire acondicionado' },
	{ name: 'Cocina equipada' },
	{ name: 'SUM' },
	{ name: 'Alarma' },
	{ name: 'Frigobar' },
	{ name: 'Sauna' },
	{ name: 'Amoblado' },
	{ name: 'Lavarropas' },
	{ name: 'Secarropas' },
	{ name: 'Caldera' },
	{ name: 'Lavavajillas' },
	{ name: 'Termotanque' },
	{ name: 'Calefacción' },
	{ name: 'Microondas' },
	{ name: 'Vigilancia' },
	{ name: 'Cancha deportes' },
	{ name: 'Quincho' },
	{ name: 'Acceso para personas con discapacidad' },
	{ name: 'Parrilla' },
	{ name: 'Solarium' },
	{ name: 'Apto profesional' },
	{ name: 'Permite mascotas' },
	{ name: 'Uso comercial' },
	{ name: 'Gimnasio' },
	{ name: 'Pileta' },
	{ name: 'Hidromasaje' },
	{ name: 'Sala de juegos' },
	{ name: 'Ascensor' },
	{ name: 'Caja fuerte' },
	{ name: 'Balcón' },
	{ name: 'Dormitorio en suite' },
	{ name: 'Living comedor' },
	{ name: 'Baulera' },
	{ name: 'Escritorio' },
];
