export const DISPONIBILIDAD_REQUEST = 'DISPONIBILIDAD_REQUEST';
export const DISPONIBILIDAD_GET_BY_AREA = 'DISPONIBILIDAD_GET_BY_AREA';
export const DISPONIBILIDAD_CREATE = 'DISPONIBILIDAD_CREATE';
export const DISPONIBILIDAD_UPDATE = 'DISPONIBILIDAD_UPDATE';
export const DISPONIBILIDAD_DELETE = 'DISPONIBILIDAD_DELETE';
export const DISPONIBILIDAD_FAIL = 'DISPONIBILIDAD_FAILURE';
