import { registerAs } from '@nestjs/config';

export default registerAs('config', () => {
	return {
		FILES_PATH: process.env.FILES_PATH,
		// -------------------------- GRAL_USERS
		GRAL_USERS_DATABASE_HOST: process.env.GRAL_USERS_DATABASE,
		GRAL_USERS_DATABASE_PORT: process.env.GRAL_USERS_DATABASE_PORT,
		GRAL_USERS_DATABASE_USERNAME: process.env.GRAL_USERS_DATABASE_USERNAME,
		GRAL_USERS_DATABASE_NAME: process.env.GRAL_USERS_DATABASE_NAME,
		GRAL_USERS_DATABASE_PASSWORD: process.env.GRAL_USERS_DATABASE_PASSWORD,
		JWT_SECRET: process.env.JWT_SECRET,
		MAILER_HOST: process.env.MAILER_HOST,
		MAILER_PORT: process.env.MAILER_PORT,
		MAILER_AUTH_USER: process.env.MAILER_AUTH_USER,
		MAILER_AUTH_PASS: process.env.MAILER_AUTH_PASS,
		FB_ID: process.env.FB_ID,
		FB_SECRET: process.env.FB_SECRET,
		FB_CALLBACK: process.env.FB_CALLBACK,
		FRONT_URL: process.env.FRONT_URL,
		GOOGLE_ID: process.env.GOOGLE_ID,
		GOOGLE_SECRET: process.env.GOOGLE_SECRET,
		GOOGLE_CALLBACK: process.env.GOOGLE_CALLBACK,
		// -------------------------- PROPERTIES
		PROPERTIES_DATABASE_HOST: process.env.PROPERTIES_DATABASE_HOST,
		PROPERTIES_DATABASE_PORT: process.env.PROPERTIES_DATABASE_PORT,
		PROPERTIES_DATABASE_USERNAME: process.env.PROPERTIES_DATABASE_USERNAME,
		PROPERTIES_DATABASE_NAME: process.env.PROPERTIES_DATABASE_USERNAME,
		PROPERTIES_DATABASE_PASSWORD: process.env.PROPERTIES_DATABASE_PASSWORD,
	};
});
