export const EVENTOS_REQUEST = 'EVENTOS_REQUEST';
export const EVENTOS_FAIL = 'EVENTOS_FAIL';
export const EVENTOS_GET_BY_ID = 'EVENTOS_GET_BY_ID';
export const EVENTOS_GET_ALL = 'EVENTOS_GET_ALL';
export const EVENTOS_ACEPTAR_RECHAZAR = 'EVENTOS_ACEPTAR_RECHAZAR';
export const EVENTOS_CLEAR = 'EVENTOS_CLEAR';
