export const CEDULA_REQUEST = 'CEDULA_REQUEST';
export const CEDULA_FAIL = 'CEDULA_FAIL';
export const CEDULA_GET_BY_ID = 'CEDULA_GET_BY_ID';
export const CEDULA_GET_BY_EMPLEADO_ID = 'CEDULA_GET_BY_EMPLEADO_ID';
export const CEDULA_GET_ALL_BY_AREA = 'CEDULA_GET_ALL_BY_AREA';

export const CEDULA_SIN_ASIGNAR = 'CEDULA_SIN_ASIGNAR';
export const CEDULA_ASIGNAR_EMPLEADO = 'CEDULA_ASIGNAR_EMPLEADO';
export const ACTUALIZAR_FECHA_RECEPCION = 'ACTUALIZAR_FECHA_RECEPCION';

export const CEDULA_PASO_SIGUIENTE = 'CEDULA_PASO_SIGUIENTE';

export const CEDULA_CREAR_NOTA = 'CEDULA_CREAR_NOTA';
export const CEDULA_ELIMINAR_NOTA = 'CEDULA_EDITAR_NOTA';

export const CEDULA_CREAR_INFORME = 'CEDULA_CREAR_INFORME';
export const CEDULA_EDITAR_INFORME = 'CEDULA_EDITAR_INFORME';
export const CEDULA_ELIMINAR_INFORME = 'CEDULA_ELIMINAR_INFORME';

export const CEDULA_GET_RELATIONS = 'CEDULA_GET_RELATIONS';
