export const TRAMITES_REQUEST = 'TRAMITES_REQUEST';
export const TRAMITES_FAIL = 'TRAMITES_FAIL';
export const TRAMITES_GET_BY_ID = 'TRAMITES_GET_BY_ID';
export const TRAMITES_GET_ALL_BY_ADMIN_ID = 'TRAMITES_GET_BY_ADMIN_ID';
export const TRAMITES_CANCELAR = 'TRAMITES_CANCELAR';

export const TRAMITES_CREATE = 'TRAMITES_CREATE';

export const TRAMITES_UPSERT_INPUTS_VALUES = 'TRAMITES_UPSERT_INPUTS_VALUES';

export const TRAMITES_GET_SIN_ASIGNAR_POR_AREA =
  'TRAMITES_GET_SIN_ASIGNAR_POR_AREA';
export const TRAMITES_ASIGNAR_EMPLEADO = 'TRAMITES_ASIGNAR_EMPLEADO';

export const TRAMITES_PASO_ANTERIOR = 'TRAMITES_PASO_ANTERIOR';
export const TRAMITES_PASO_SIGUIENTE = 'TRAMITES_PASO_SIGUIENTE';
export const TRAMITES_GOTO_PASO = 'TRAMITE_GOTO_PASO';

export const TRAMITES_CREAR_INFORME = 'TRAMITES_CREAR_INFORME';
export const TRAMITES_UPDATE_INFORME = 'TRAMITES_UPDATE_INFORME';
export const TRAMITES_DELETE_INFORME = 'TRAMITES_DELETE_INFORME';

export const TRAMITES_CREAR_RESOLUCION = 'TRAMITES_CREAR_RESOLUCION';
export const TRAMITES_UPDATE_RESOLUCION = 'TRAMITES_UPDATE_RESOLUCION';
export const TRAMITES_DELETE_RESOLUCION = 'TRAMITES_DELETE_RESOLUCION';

export const TRAMITES_CREAR_INTIMACION = 'TRAMITES_CREAR_INTIMACION';
export const TRAMITES_UPDATE_INTIMACION = 'TRAMITES_UPDATE_INTIMACION';
export const TRAMITES_DELETE_INTIMACION = 'TRAMITES_DELETE_INTIMACION';

export const TRAMITES_CREAR_DICTAMEN = 'TRAMITES_CREAR_DICTAMEN';
export const TRAMITES_UPDATE_DICTAMEN = 'TRAMITES_UPDATE_DICTAMEN';
export const TRAMITES_DELETE_DICTAMEN = 'TRAMITES_DELETE_DICTAMEN';

export const TRAMITES_GET_ALL_BY_AREA = 'TRAMITES_GET_ALL_BY_AREA';
export const TRAMITES_APROBAR_POR_AREA = 'TRAMITES_APROBAR_POR_AREA';
export const TRAMITES_RECHAZAR_POR_AREA = 'TRAMITES_RECHAZAR_POR_AREA';
export const TRAMITES_SOLICITAR_MODIFICACION_POR_AREA =
  'TRAMITES_SOLICITAR_MODIFICACION_POR_AREA';

export const TRAMITES_RECHAZAR_TRAMITE = 'TRAMITES_RECHAZAR_TRAMITE';

export const TRAMITES_CREAR_NOTA = 'TRAMITES_CREAR_NOTA';
export const TRAMITES_DELETE_NOTA = 'TRAMITES_DELETE_NOTA';

export const TRAMITES_CREAR_ARCHIVO = 'TRAMITES_CREAR_ARCHIVO';
export const TRAMITES_DELETE_ARCHIVO = 'TRAMITES_DELETE_ARCHIVO';

export const TRAMITE_GET_RELATIONS = 'TRAMITE_GET_RELATIONS';

export const TRAMITE_CREAR_CEDULA = 'TRAMITE_CREAR_CEDULA';
