export const barrios = [
  { value: 1, label: "Agronomía", tag: "agronomia" },
  { value: 2, label: "Almagro", tag: "almagro" },
  { value: 3, label: "Balvanera", tag: "balvanera" },
  { value: 4, label: "Barracas", tag: "barracas" },
  { value: 5, label: "Belgrano", tag: "belgrano" },
  { value: 6, label: "Boedo", tag: "boedo" },
  { value: 7, label: "Caballito", tag: "caballito" },
  { value: 8, label: "Chacarita", tag: "chacarita" },
  { value: 9, label: "Coghlan", tag: "coghlan" },
  { value: 10, label: "Colegiales", tag: "colegiales" },
  { value: 11, label: "Constitución", tag: "constitucion" },
  { value: 12, label: "Flores", tag: "flores" },
  { value: 13, label: "Floresta", tag: "floresta" },
  { value: 14, label: "La Boca", tag: "la%20boca" },
  { value: 16, label: "Liniers", tag: "liniers" },
  { value: 17, label: "Mataderos", tag: "mataderos" },
  { value: 18, label: "Monte Castro", tag: "monte%20castro" },
  { value: 19, label: "Monserrat", tag: "monserrat" },
  { value: 20, label: "Nueva Pompeya", tag: "nueva%20pompeya" },
  { value: 21, label: "Núñez", tag: "nunez" },
  { value: 22, label: "Palermo", tag: "palermo" },
  { value: 23, label: "Parque Avellaneda", tag: "parque%20avellaneda" },
  { value: 24, label: "Parque Chacabuco", tag: "parque%20chacabuco" },
  { value: 25, label: "Parque Chas", tag: "parque%20chas" },
  { value: 26, label: "Parque Patricios", tag: "parque%20patricios" },
  { value: 15, label: "Paternal", tag: "la%20paternal" },
  { value: 27, label: "Puerto Madero", tag: "puerto%20madero" },
  { value: 28, label: "Recoleta", tag: "recoleta" },
  { value: 29, label: "Retiro", tag: "retiro" },
  { value: 30, label: "Saavedra", tag: "saavedra" },
  { value: 31, label: "San Cristóbal", tag: "san%20cristobal" },
  { value: 32, label: "San Nicolás", tag: "san%20nicolas" },
  { value: 33, label: "San Telmo", tag: "san%20telmo" },
  { value: 34, label: "Versalles", tag: "versalles" },
  { value: 35, label: "Villa Crespo", tag: "villa%20crespo" },
  { value: 36, label: "Villa Devoto", tag: "villa%20devoto" },
  { value: 37, label: "Villa General Mitre", tag: "villa%20general%20mitre" },
  { value: 38, label: "Villa Lugano", tag: "villa%20lugano" },
  { value: 39, label: "Villa Luro", tag: "villa%20luro" },
  { value: 40, label: "Villa Ortúzar", tag: "villa%20ortuzar" },
  { value: 41, label: "Villa Pueyrredón", tag: "villa%20pueyrredon" },
  { value: 42, label: "Villa Real", tag: "villa%20real" },
  { value: 43, label: "Villa Riachuelo", tag: "villa%20riachuelo" },
  { value: 44, label: "Villa Santa Rita", tag: "villa%20santa%20rita" },
  { value: 45, label: "Villa Soldati", tag: "villa%20soldati" },
  { value: 46, label: "Villa Urquiza", tag: "villa%20urquiza" },
  { value: 47, label: "Villa del Parque", tag: "villa%20del%20parque" },
  { value: 48, label: "Vélez Sarsfield", tag: "velez%20sarsfield" },
];

export const popularBarrios = [
  { value: 22, label: "Palermo", tag: "palermo" },
  { value: 28, label: "Recoleta", tag: "recoleta" },
  { value: 5, label: "Belgrano", tag: "belgrano" },
  { value: 7, label: "Caballito", tag: "caballito" },
  { value: 21, label: "Nuñez", tag: "nunez" },
  { value: "", label: "Todos los barrios", tag: "" },
];

export const properties = [
  {
    value: 9,
    label: "Bodega/Galpón/Depósito",
    tag: "bodega_galpon_deposito",
    plural: "Bodegas/Galpones/Depósitos",
  },
  {
    value: 13,
    label: "Bóveda/Nicho/Parcela",
    tag: "boveda_nicho_parcela",
    plural: "Bóvedas/Nichos/Parcelas",
  },
  { value: 2, label: "Casa", tag: "casa", plural: "Casas" },
  { value: 4, label: "Cochera", tag: "cochera", plural: "Cocheras" },
  {
    value: 5,
    label: "Consultorio",
    tag: "consultorio",
    plural: "Consultorios",
  },
  {
    value: 1,
    label: "Departamento",
    tag: "departamento",
    plural: "Departamentos",
  },
  { value: 12, label: "Edificio", tag: "edificio", plural: "edificios" },
  {
    value: 6,
    label: "Fondo de comercio",
    tag: "fondo%20de%20comercio",
    plural: "Fondos de comercio",
  },
  { value: 11, label: "Hotel", tag: "hotel", plural: "hoteles" },
  {
    value: 7,
    label: "Local comercial",
    tag: "local%20comercial",
    plural: "Locales comerciales",
  },
  {
    value: 8,
    label: "Oficina comercial",
    tag: "oficina_comercial",
    plural: "Oficinas comerciales",
  },
  { value: 3, label: "PH", tag: "ph", plural: "PHs" },
  { value: 10, label: "Terreno", tag: "terreno", plural: "Terrenos" },
];

export const operations = [
  { value: 1, label: "Compra", tag: "compra" },
  { value: 2, label: "Alquiler", tag: "alquiler" },
  { value: 3, label: "Temporario", tag: "temporario" },
];

export const ambiences = [
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 0,
    label: "Seleccionar ambientes",
  },
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 1,
    label: "1 Ambiente",
  },
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 2,
    label: "2 Ambientes",
  },
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 3,
    label: "3 Ambientes",
  },
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 4,
    label: "4 Ambientes",
  },
  {
    name: "Ambientes",
    tag: "ambientes",
    value: 5,
    label: "5+ Ambientes",
  },
];

export const bathrooms = [
  {
    name: "Baños",
    tag: "banios",
    value: 0,
    label: "Seleccionar baños",
  },
  {
    name: "Baños",
    tag: "banios",
    value: 1,
    label: "1 Baño",
  },
  {
    name: "Baños",
    tag: "banios",
    value: 2,
    label: "2 Baños",
  },
  {
    name: "Baños",
    tag: "banios",
    value: 3,
    label: "3 Baños",
  },
  {
    name: "Baños",
    tag: "banios",
    value: 4,
    label: "4 Baños",
  },
  {
    name: "Baños",
    tag: "banios",
    value: 5,
    label: "5+ Baños",
  },
];

export const bedrooms = [
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 0,
    label: "Seleccionar habitaciones",
  },
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 1,
    label: "1 Habitación",
  },
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 2,
    label: "2 Habitaciones",
  },
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 3,
    label: "3 Habitaciones",
  },
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 4,
    label: "4 Habitaciones",
  },
  {
    name: "Habitaciones",
    tag: "habitaciones",
    value: 5,
    label: "5+ Habitaciones",
  },
];

export const garages = [
  {
    name: "Garages",
    tag: "cocheras",
    value: 0,
    label: "Seleccionar cocheras",
  },
  {
    name: "Garages",
    tag: "cocheras",
    value: 1,
    label: "1 Cochera",
  },
  {
    name: "Garages",
    tag: "cocheras",
    value: 2,
    label: "2 Cocheras",
  },
  {
    name: "Garages",
    tag: "cocheras",
    value: 3,
    label: "3 Cocheras",
  },
  {
    name: "Garages",
    tag: "cocheras",
    value: 4,
    label: "4 Cocheras",
  },
  {
    name: "Garages",
    tag: "cocheras",
    value: 5,
    label: "5+ Cocheras",
  },
];

export const price = [
  { currency: "USD", tag: "dolares", min: "", max: "" },
  { currency: "ARS", tag: "pesos", min: "", max: "" },
];

export const surface = [
  {
    type: "coveredSurface",
    tag: "superficieCubierta",
    label: "Cubierta",
    min: "",
    max: "",
  },
  {
    type: "totalSurface",
    tag: "superficieTotal",
    label: "Total",
    min: "",
    max: "",
  },
];

export const apartmentExtras = {
  property_type: 1,
  caracteristicasGenerales: [
    {
      id: 1,
      name: "Acceso para personas con discapacidad",
      label: "acceso_p_personas_c_discap",
    },
    { id: 4, name: "Apto profesional", label: "apto_profesional" },
    { id: 7, name: "Gimnasio", label: "gimnasio" },
    { id: 9, name: "Hidromasaje", label: "hidromasaje" },
    { id: 2, name: "Parrilla", label: "parrilla" },
    { id: 5, name: "Permite mascotas", label: "permite_mascotas" },
    { id: 8, name: "Pileta", label: "pileta" },
    { id: 10, name: "Sala de juegos", label: "sala_de_juegos" },
    { id: 3, name: "Solarium", label: "solarium" },
    { id: 6, name: "Uso comercial", label: "uso_comercial" },
  ],
  caracteristicas: [
    { id: 11, name: "Aire acondicionado", label: "aire" },
    { id: 14, name: "Alarma", label: "alarma" },
    { id: 17, name: "Amoblado", label: "amoblado" },
    { id: 20, name: "Caldera", label: "Caldera" },
    { id: 23, name: "Calefacción", label: "calefacción" },
    { id: 26, name: "Cancha deportes", label: "cancha_deportes" },
    { id: 12, name: "Cocina equipada", label: "cocina_equipada" },
    { id: 15, name: "Frigobar", label: "frigobar" },
    { id: 51, name: "Fuerza motriz", label: "fuerza_motriz" },
    { id: 50, name: "Grúa", label: "grua" },
    { id: 58, name: "Grupo electrógeno", label: "grupo_electrógeno" },
    { id: 18, name: "Lavarropas", label: "lavarropas" },
    { id: 21, name: "Lavavajillas", label: "lavavajillas" },
    { id: 24, name: "Microondas", label: "microondas" },
    { id: 54, name: "Motores", label: "motores" },
    { id: 49, name: "Plaza de maniobras", label: "plaza_de_maniobras" },
    { id: 27, name: "Quincho", label: "quincho" },
    { id: 16, name: "Sauna", label: "sauna" },
    { id: 19, name: "Secarropas", label: "secarropas" },
    { id: 13, name: "SUM", label: "sum" },
    { id: 22, name: "Termotanque", label: "termotanque" },
    { id: 25, name: "Vigilancia", label: "vigilancia" },
  ],
  servicios: [
    { id: 28, name: "Ascensor", label: "ascensor" },
    { id: 57, name: "Cable", label: "cable" },
    { id: 29, name: "Caja fuerte", label: "caja_fuerte" },
    { id: 55, name: "Internet", label: "internet" },
    { id: 30, name: "Laundry", label: "laundry" },
    { id: 56, name: "Wifi", label: "wifi" },
  ],
  ambientes: [
    { id: 31, name: "Balcón", label: "balcon" },
    { id: 34, name: "Baulera", label: "baulera" },
    { id: 37, name: "Cocina", label: "cocina" },
    { id: 40, name: "Comedor", label: "comedor" },
    { id: 43, name: "Comedor de diario", label: "comedor_de_diario" },
    {
      id: 46,
      name: "Dependencia de servicio",
      label: "dependencia_de_servicio",
    },
    { id: 32, name: "Dormitorio en suite", label: "dormitorio_en_suite" },
    { id: 35, name: "Escritorio", label: "escritorio" },
    { id: 38, name: "Hall", label: "hall" },
    { id: 41, name: "Jardín", label: "jardin" },
    { id: 44, name: "Lavadero", label: "lavadero" },
    { id: 47, name: "Living", label: "living" },
    { id: 33, name: "Living comedor", label: "living_comedor" },
    { id: 52, name: "Oficinas", label: "oficinas" },
    { id: 36, name: "Patio", label: "patio" },
    { id: 39, name: "Sótano", label: "sotano" },
    { id: 42, name: "Terraza", label: "terraza" },
    { id: 45, name: "Toilette", label: "toilette" },
    { id: 48, name: "Vestidor", label: "vestidor" },
    { id: 53, name: "Vestuarios", label: "vestuarios" },
  ],
};

export const sortByFavorites = [
  { value: 1, label: "Últimas guardadas" },
  { value: 2, label: "Primeras guardadas" },
  { value: 3, label: "Menor precio" },
  { value: 4, label: "Mayor precio" },
  { value: 5, label: "Nombre A-Z" },
  { value: 6, label: "Nombre Z-A" },
];

export const sortBySearches = [
  { value: 1, label: "Últimas guardadas" },
  { value: 2, label: "Primeras guardadas" },
  { value: 5, label: "Nombre A-Z" },
  { value: 6, label: "Nombre Z-A" },
];

export const alerts = [
  { value: 1, label: "Sin alertas" },
  { value: 2, label: "Inmediata" },
  { value: 3, label: "Diaria" },
];

export const totalExtras = [
  {
    id: 1,
    name: "Acceso para personas con discapacidad",
    label: "acceso_p_personas_c_discap",
  },
  { id: 2, name: "Parrilla", label: "parrilla" },
  { id: 3, name: "Solarium", label: "solarium" },
  { id: 4, name: "Apto profesional", label: "apto_profesional" },
  { id: 5, name: "Permite mascotas", label: "permite_mascotas" },
  { id: 6, name: "Uso comercial", label: "uso_comercial" },
  { id: 7, name: "Gimnasio", label: "gimnasio" },
  { id: 8, name: "Pileta", label: "pileta" },
  { id: 9, name: "Hidromasaje", label: "hidromasaje" },
  { id: 10, name: "Sala de juegos", label: "sala_de_juegos" },
  { id: 11, name: "Aire acondicionado", label: "aire" },
  { id: 12, name: "Cocina equipada", label: "cocina_equipada" },
  { id: 13, name: "SUM", label: "sum" },
  { id: 14, name: "Alarma", label: "alarma" },
  { id: 15, name: "Frigobar", label: "frigobar" },
  { id: 16, name: "Sauna", label: "sauna" },
  { id: 17, name: "Amoblado", label: "amoblado" },
  { id: 18, name: "Lavarropas", label: "lavarropas" },
  { id: 19, name: "Secarropas", label: "secarropas" },
  { id: 20, name: "Caldera", label: "Caldera" },
  { id: 21, name: "Lavavajillas", label: "lavavajillas" },
  { id: 22, name: "Termotanque", label: "termotanque" },
  { id: 23, name: "Calefacción", label: "calefacción" },
  { id: 24, name: "Microondas", label: "microondas" },
  { id: 25, name: "Vigilancia", label: "vigilancia" },
  { id: 26, name: "Cancha deportes", label: "cancha_deportes" },
  { id: 27, name: "Quincho", label: "quincho" },
  { id: 28, name: "Ascensor", label: "ascensor" },
  { id: 29, name: "Caja fuerte", label: "caja_fuerte" },
  { id: 30, name: "Laundry", label: "laundry" },
  { id: 31, name: "Balcón", label: "balcon" },
  { id: 32, name: "Dormitorio en suite", label: "dormitorio_en_suite" },
  { id: 33, name: "Living comedor", label: "living_comedor" },
  { id: 34, name: "Baulera", label: "baulera" },
  { id: 35, name: "Escritorio", label: "escritorio" },
  { id: 36, name: "Patio", label: "patio" },
  { id: 37, name: "Cocina", label: "cocina" },
  { id: 38, name: "Hall", label: "hall" },
  { id: 39, name: "Sótano", label: "sotano" },
  { id: 40, name: "Comedor", label: "comedor" },
  { id: 41, name: "Jardín", label: "jardin" },
  { id: 42, name: "Terraza", label: "terraza" },
  { id: 43, name: "Comedor de diario", label: "comedor_de_diario" },
  { id: 44, name: "Lavadero", label: "lavadero" },
  { id: 45, name: "Toilette", label: "toilette" },
  {
    id: 46,
    name: "Dependencia de servicio",
    label: "dependencia_de_servicio",
  },
  { id: 47, name: "Living", label: "living" },
  { id: 48, name: "Vestidor", label: "vestidor" },
  { id: 49, name: "Plaza de maniobras", label: "plaza_de_maniobras" },
  { id: 50, name: "Grúa", label: "grua" },
  { id: 51, name: "Fuerza motriz", label: "fuerza_motriz" },
  { id: 52, name: "Oficinas", label: "oficinas" },
  { id: 53, name: "Vestuarios", label: "vestuarios" },
  { id: 54, name: "Motores", label: "motores" },
  { id: 55, name: "Internet", label: "internet" },
  { id: 56, name: "Wifi", label: "wifi" },
  { id: 57, name: "Cable", label: "cable" },
  { id: 58, name: "Grupo electrógeno", label: "grupo_electrógeno" },
];

export const extrasArray = [
  {
    id: "extras1",
    label: "Características Generales",
    content: apartmentExtras.caracteristicasGenerales,
  },
  {
    id: "extras2",
    label: "Características",
    content: apartmentExtras.caracteristicas,
  },
  {
    id: "extras3",
    label: "Servicios",
    content: apartmentExtras.servicios,
  },
  {
    id: "extras4",
    label: "Ambientes",
    content: apartmentExtras.ambientes,
  },
];
