export const PROCESO_LEGALES_REQUEST = 'PROCESO_LEGALES_REQUEST';
export const PROCESO_LEGALES_FAIL = 'PROCESO_LEGALES_FAIL';

export const PROCESO_LEGALES_CREAR = 'PROCESO_LEGALES_CREAR';
export const PROCESO_LEGALES_CANCELAR = 'PROCESO_LEGALES_CANCELAR';

export const PROCESO_LEGALES_CREAR_FALLO = 'PROCESO_LEGALES_CREAR_FALLO';
export const PROCESO_LEGALES_UPDATE_FALLO = 'PROCESO_LEGALES_UPDATE_FALLO';
export const PROCESO_LEGALES_DELETE_FALLO = 'PROCESO_LEGALES_DELETE_FALLO';

export const PROCESO_LEGALES_CREAR_RESOLUCION =
  'PROCESO_LEGALES_CREAR_RESOLUCION';
export const PROCESO_LEGALES_UPDATE_RESOLUCION =
  'PROCESO_LEGALES_UPDATE_RESOLUCION';
export const PROCESO_LEGALES_DELETE_RESOLUCION =
  'PROCESO_LEGALES_DELETE_RESOLUCION';

export const PROCESO_LEGALES_CREAR_DICTAMEN = 'PROCESO_LEGALES_CREAR_DICTAMEN';
export const PROCESO_LEGALES_UPDATE_DICTAMEN =
  'PROCESO_LEGALES_UPDATE_DICTAMEN';
export const PROCESO_LEGALES_DELETE_DICTAMEN =
  'PROCESO_LEGALES_DELETE_DICTAMEN';

export const PROCESO_LEGALES_CREAR_INFORME = 'PROCESO_LEGALES_CREAR_INFORME';
export const PROCESO_LEGALES_UPDATE_INFORME = 'PROCESO_LEGALES_UPDATE_INFORME';
export const PROCESO_LEGALES_DELETE_INFORME = 'PROCESO_LEGALES_DELETE_INFORME';

export const PROCESO_LEGALES_CREAR_NOTA = 'PROCESO_LEGALES_CREAR_NOTA';
export const PROCESO_LEGALES_DELETE_NOTA = 'PROCESO_LEGALES_DELETE_NOTA';

export const PROCESO_LEGALES_CREAR_CEDULA = 'PROCESO_LEGALES_CREAR_CEDULA';

export const PROCESO_LEGALES_CREAR_ARCHIVO = 'PROCESO_LEGALES_CREAR_ARCHIVO';
export const PROCESO_LEGALES_DELETE_ARCHIVO = 'PROCESO_LEGALES_DELETE_ARCHIVO';

export const PROCESO_LEGALES_PASO_ANTERIOR = 'PROCESO_LEGALES_PASO_ANTERIOR';
export const PROCESO_LEGALES_PASO_SIGUIENTE = 'PROCESO_LEGALES_PASO_SIGUIENTE';
export const PROCESO_LEGALES_APROBAR_POR_AREA =
  'PROCESO_LEGALES_APROBAR_POR_AREA';
export const PROCESO_LEGALES_RECHAZAR_POR_AREA =
  'PROCESO_LEGALES_RECHAZAR_POR_AREA';

export const PROCESO_LEGALES_GET_IMPUTACIONES =
  'PROCESO_LEGALES_GET_IMPUTACIONES';

export const PROCESO_LEGALES_CREAR_DESPACHO_IMPUTACION =
  'PROCESO_LEGALES_CREAR_DESPACHO_IMPUTACION';
export const PROCESO_LEGALES_UPDATE_DESPACHO_IMPUTACION =
  'PROCESO_LEGALES_UPDATE_DESPACHO_IMPUTACION';
export const PROCESO_LEGALES_DELETE_DESPACHO_IMPUTACION =
  'PROCESO_LEGALES_DELETE_DESPACHO_IMPUTACION';
