//create types from ./index.js

export const FISCALIZACION_REQUEST = 'FISCALIZACION_REQUEST';
export const FISCALIZACION_FAIL = 'FISCALIZACION_FAIL';

export const FISCALIZACION_CREATE = 'FISCALIZACION_CREATE';

export const FISCALIZACION_UPSERT_INPUTS_VALUES =
  'FISCALIZACION_UPSERT_INPUTS_VALUES';

export const FISCALIZACION_CREAR_CEDULA = 'FISCALIZACION_CREAR_CEDULA';

export const FISCALIZACION_CREAR_NOTA = 'FISCALIZACION_CREAR_NOTA';
export const FISCALIZACION_DELETE_NOTA = 'FISCALIZACION_DELETE_NOTA';

export const FISCALIZACION_CREAR_CONSTATACION =
  'FISCALIZACION_CREAR_CONSTATACION';
export const FISCALIZACION_UPDATE_CONSTATACION =
  'FISCALIZACION_UPDATE_CONSTATACION';
export const FISCALIZACION_DELETE_CONSTATACION =
  'FISCALIZACION_DELETE_CONSTATACION';

export const FISCALIZACION_GET_CONCEPTOS = 'FISCALIZACION_GET_CONCEPTOS';

export const FISCALIZACION_CREAR_COBRO = 'FISCALIZACION_CREAR_COBRO';
export const FISCALIZACION_UPDATE_COBRO = 'FISCALIZACION_UPDATE_COBRO';
export const FISCALIZACION_DELETE_COBRO = 'FISCALIZACION_DELETE_COBRO';

export const FISCALIZACION_CREAR_TRANSACCION =
  'FISCALIZACION_CREAR_TRANSACCION';
export const FISCALIZACION_DELETE_TRANSACCION =
  'FISCALIZACION_DELETE_TRANSACCION';

export const FISCALIZACION_CANCELAR = 'FISCALIZACION_CANCELAR';
export const FISCALIZACION_FINALIZAR = 'FISCALIZACION_FINALIZAR';

export const FISCALIZACION_CREAR_INFORME = 'FISCALIZACION_CREAR_INFORME';
