export const TRANSACCION_REQUEST = 'TRANSACCION_REQUEST';
export const TRANSACCION_FAIL = 'TRANSACCION_FAIL';
export const TRANSACCION_GET_BY_ID = 'TRANSACCION_GET_BY_ID';
export const TRANSACCION_GET_ALL_BY_ADMIN_ID = 'TRANSACCION_GET_BY_ADMIN_ID';
export const TRANSACCION_APROBAR_RECHAZAR = 'TRANSACCION_APROBAR_RECHAZAR';
export const TRANSACCION_GET_ALL = 'TRANSACCION_GET_ALL';
export const TRANSACCION_UPLOAD_PAYMENT = 'TRANSACCION_UPLOAD_PAYMENT';
