export const SA_REQUEST = 'SA_REQUEST';
export const SA_FAIL = 'SA_FAIL';

export const SA_GET_ROLES = 'SA_GET_ROLES';
export const SA_CREATE_ROL = 'SA_CREATE_ROL';
export const SA_UPDATE_ROL = 'SA_UPDATE_ROL';
export const SA_DELETE_ROL = 'SA_DELETE_ROL';

export const SA_GET_PERMISSIONS = 'SA_GET_PERMISSIONS';

export const SA_GET_EMPLEADOS = 'SA_GET_EMPLEADOS';
export const SA_CREATE_EMPLEADO = 'SA_CREATE_EMPLEADO';
export const SA_DELETE_EMPLEADO = 'SA_DELETE_EMPLEADO';

export const SA_GET_AREAS = 'SA_GET_AREAS';

export const SA_GET_ALL_TRAMITES = 'SA_GET_ALL_TRAMITES';

export const SA_GET_CONFIGURATION = 'SA_GET_CONFIGURATION';
export const SA_UPDATE_CONFIGURATION = 'SA_UPDATE_CONFIGURATION';
