export const NOTIFICATIONS_REQUEST = 'NOTIFICATIONS_REQUEST';
export const NOTIFICATIONS_ERROR = 'NOTIFICATIONS_ERROR';
export const NOTIFICATIONS_BY_USERID = 'NOTIFICATIONS_BY_USERID';
export const NOTIFICATIONS_MARK_ALL_AS_READ = 'NOTIFICATIONS_MARK_ALL_AS_READ';
export const NOTIFICATIONS_MARK_AS_READ = 'NOTIFICATIONS_MARK_AS_READ';
export const NOTIFICATIONS_MARK_ALL_AS_SEEN = 'NOTIFICATIONS_MARK_ALL_AS_SEEN';
