export const EXPEDIENTES_REQUEST = 'EXPEDIENTES_REQUEST';
export const EXPEDIENTES_FAIL = 'EXPEDIENTES_FAIL';

export const EXPEDIENTES_CREATE = 'EXPEDIENTES_CREATE';
export const EXPEDIENTE_FINALIZAR = 'EXPEDIENTE_FINALIZAR';

export const EXPEDIENTES_GET_BY_ID = 'EXPEDIENTES_GET_BY_ID';
export const EXPEDIENTES_GET_ALL_BY_AREA = 'EXPEDIENTES_GET_ALL_BY_AREA';
export const EXPEDIENTES_GET_ALL_BY_ADMIN_ID = 'EXPEDIENTES_GET_BY_ADMIN_ID';
export const EXPEDIENTES_GET_SIN_ASIGNAR_POR_AREA =
  'EXPEDIENTES_GET_SIN_ASIGNAR_POR_AREA';

export const EXPEDIENTES_ASIGNAR_EMPLEADO = 'EXPEDIENTES_ASIGNAR_EMPLEADO';

export const EXPEDIENTES_CAMBIAR_AREA = 'EXPEDIENTES_CAMBIAR_AREA';

export const EXPEDIENTES_CREAR_NOTA = 'EXPEDIENTES_CREAR_NOTA';
export const EXPEDIENTES_DELETE_NOTA = 'EXPEDIENTES_DELETE_NOTA';

export const EXPEDIENTES_CREAR_ARCHIVO = 'EXPEDIENTES_CREAR_ARCHIVO';
export const EXPEDIENTES_DELETE_ARCHIVO = 'EXPEDIENTES_DELETE_ARCHIVO';

export const EXPEDIENTES_CREAR_IFORME = 'EXPEDIENTES_CREAR_IFORME';
export const EXPEDIENTES_UPDATE_IFORME = 'EXPEDIENTES_UPDATE_IFORME';
export const EXPEDIENTES_DELETE_IFORME = 'EXPEDIENTES_DELETE_IFORME';

export const EXPEDIENTE_GET_RELATIONS = 'EXPEDIENTE_GET_RELATIONS';

export const EXPEDIENTE_CREAR_CARATULA = 'EXPEDIENTE_CREAR_CARATULA';
